modLoader = "javafml"
loaderVersion = "[47,)"
license = "LGPL-3.0-only"

[[mods]]
modId = "justcoordinates"
version = "${version}"
displayName = "Just Coordinates"
description = "Displays simple XYZ coordinates on screen."

[[dependencies.justcoordinates]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.justcoordinates]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}, 1.21)"
ordering = "NONE"
side = "CLIENT"
